In [1]:
#install numpy
%pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 5.4 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.3 MB 8.2 MB/s eta 0:00:02
   ------------- -------------------------- 4.2/12.3 MB 7.9 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.3 MB 7.8 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.3 MB 7.8 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.3 MB 7.8 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.3 MB 7.8 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 7.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
print(np.__version__)

2.4.2


In [3]:
# 1D
data = np.array([21,22,23,24,25])
print(data)
print(data[2])
print(data.shape)
print(data.ndim)

[21 22 23 24 25]
23
(5,)
1


In [4]:
# 2D
data = np.array([[21,22,23,24],[25,26,27,28],[29,30,31,32]])
print(data)
print(data.shape)
print(data.ndim)
print(print(data[1][2]))

[[21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]
(3, 4)
2
27
None


In [5]:
# 3D
data = np.array([
    [[21,22,23,24],[25,26,27,28],[29,30,31,32]],
    [[210,220,230,240],[250,260,270,280],[290,300,310,320]]
])
print(data)
print(data.shape)
print(data.ndim)
print(data[1][1][0])
print(data[0][1][0])

[[[ 21  22  23  24]
  [ 25  26  27  28]
  [ 29  30  31  32]]

 [[210 220 230 240]
  [250 260 270 280]
  [290 300 310 320]]]
(2, 3, 4)
3
250
25


In [6]:
data = [21,22,23,24,25,26,27,28]
print(type(data))
arr = np.array(data)
print(type(arr))
print(data)
print(arr)

<class 'list'>
<class 'numpy.ndarray'>
[21, 22, 23, 24, 25, 26, 27, 28]
[21 22 23 24 25 26 27 28]


In [7]:
data = np.array([[21,22,23],[24,25,26],[27,28,29]])
print(data)

[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [8]:
print(data[1][2])

26


In [10]:
data = np.array([[[21,22,23],[24,25,26],[27,28,29]],[[210,220,230],[240,250,260],[270,280,290]]])
print(data)

[[[ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]]

 [[210 220 230]
  [240 250 260]
  [270 280 290]]]


In [11]:
print(data[1][2])

[270 280 290]
